### ISSUE TITLE
Travel & Notes not in English

### ISSUE THREAD

**Issue by perchslayer** [wwwouaiebe/leaflet.TravelNotes#57]
All items on map are in English, but the directions (Travel & Notes) are in French and I can't seem to locate where that is switched or maintained.

**Comment by wwwouaiebe** [comment]
You have two ways to change the language for TravelNotes:
- you can add the language directly in url's parameters. So, if you are using the demo, the complete url for english is https://wwwouaiebe.github.io/leaflet.TravelNotes/?lng=en
- now if you have made your owm installation for TravelNotes, you can force the default language to english: edit the file TravelNotesConfig.json and changes the language from "fr" to "en" at line 14.
 The language given in the url or in the TravelNotesConfig.json is also used for directions, so if you are using Mapbox or OSRM, directions must be in fr or en, depending of your choices.

**Comment by wwwouaiebe** [comment]
V1.4.0 released
